#!/usr/bin/python3
# This code write by Mr.nope
import os
import time
import sys
try:
   import subprocess
except:
    os.system("pip install subprocess")
    import subprocess
try_to_sm_sey = "\nSM.Sey: Please Usage: --help\n"
error_SM_sey_argument = "\nPlease Chech Argument!\nAnd Usage: --help\n"
SM_sey_argument_2 = "\nPlease Check Argument!\nAnd, Usage: --help for Help\n"
def arg():
    if sys.argv[1] == '-f':
      if sys.argv[2] == 'din':
        print("""
        ─────▄████▀█▄
        ───▄█████████████████▄
        ─▄█████.▼.▼.▼.▼.▼.▼▼▼▼  < """ + sys.argv[3] + """ >
        ▄███████▄.▲.▲▲▲▲▲▲▲▲
        ████████████████████▀▀
""")
        sys.exit()
      elif sys.argv[2] == 'com':
          print("""
        ▐▓█▀▀▀▀▀▀▀▀▀█▓▌░▄▄▄▄▄░
        ▐▓█░░▀░░▀▄░░█▓▌░█▄▄▄█░ < """ + sys.argv[3] + """ >
        ▐▓█░░▄░░▄▀░░█▓▌░█▄▄▄█░
        ▐▓█▄▄▄▄▄▄▄▄▄█▓▌░█████░
        ░░░░▄▄███▄▄░░░░░█████░
""")
          sys.exit()
      elif sys.argv[2] == 'phone':
          print("""
        ────▄▄▄▄▄▄▄▄▄▄▄▄▄▄
        ▀▀▀█─▄▄▄▄▄▄─▄─▄─▄─█ < """ + sys.argv[3] + """ >
        ───█─█────█─▄▀▄▀▄─█
        ───█─█▄▄▄▄█─▄▀▄▀▄─█
        ───▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀
""")
          sys.exit()
      elif sys.argv[2] == 'live':
          print("""
        ──────▄▀─
        ─█▀▀▀█▀█─
        ──▀▄░▄▀──
        ────█────
        ──▄▄█▄▄──
          """ + sys.argv[3] + "\n")
          sys.exit()
      elif sys.argv[2] == 'face':
          print("""
        ──────────────────────────────────
        ─────────▄▄───────────────────▄▄──
        ──────────▀█───────────────────▀█─
        ──────────▄█───────────────────▄█─
        ──█████████▀───────────█████████▀─
        ───▄██████▄─────────────▄██████▄──
        ─▄██▀────▀██▄─────────▄██▀────▀██▄
        ─██────────██─────────██────────██
        ─██───██───██─────────██───██───██    """ + sys.argv[3] + """
        ─██────────██─────────██────────██
        ──██▄────▄██───────────██▄────▄██─
        ───▀██████▀─────────────▀██████▀──
        ──────────────────────────────────
        ──────────────────────────────────
        ──────────────────────────────────
        ───────────█████████████──────────
        ──────────────────────────────────
        ──────────────────────────────────
""")
          sys.exit()
      else:
          print(SM_sey_argument_2)
          sys.exit()
    elif sys.argv[1] == '--help':
        print("""
This code write by Mr.nope
Usage:
------------------------------------------------------
usage:                                                |
     smsey -f com word and make computer Art          |
     smsey -f din word and make dinosour game Art     |
     smsey -f live word and make live Art             |
     smsey -f face word and make face Art             |
     smsey -f phone word and make phone Art           |
-------------------------------------------------------
""")
        sys.exit()
    elif sys.argv[1] == '--version':
        sm_sey_version()
    elif sys.argv[1] == sys.argv[1]:
        print("""
SM-Sey Argument: """ + sys.argv[1])
        sys.exit()
    else:
        print(error_SM_sey_argument)
        sys.exit()
def sm_sey_version():
    print("""
SM-Sey 1.3.0
""")
if __name__ == '__main__':
  try:
     arg()
  except IndexError:
      print(try_to_sm_sey)
